server:
  port: 8080

spring:
  application:
    name: tow-truck-bot

telegram:
  web:
    bot-username: CarTowTruckBot
    admin-chat-id: 7895027135
    auth:
      token: ${WEB_TELEGRAM_AUTH_TOKEN}
    hook:
      url: https://tow-truck-bot.nl.tuna.am/api/telegram/webhook
      secret: ser_aleu_3d2a09d1-1994-482a-87b2-b9f647e64e30
  steps:
    start:
      message: |
        семки есть?
      button: отдать семки
      image-path: src/main/resources/telegram/start_image.jpg
    options:
      error-text: |
        Упс, мне смазывают шестеренки, позвоните, пожалуйста по этому номеру для заказа эвакуатора: 8(909)-999-99-99
      message: |
        тебе чего?
      dishes:
        message: |
          Тестовое сообщение
        button: Нажми сюда, дружок
      option1:
        button: push 1
      option2:
        button: push 2
  forbidden-words:
    is_enabled: true
    path: src/main/resources/telegram/forbidden_words.txt
  black-listed-telegram-names:
    path: src/main/resources/telegram/black_listed_telegram_names.txt