server:
  port: 8080

spring:
  application:
    name: tow-truck-bot

telegram:
  web:
    bot-username: CarTowTruckBot
    admin-chat-id: 1026435138
    auth:
      token: ${WEB_TELEGRAM_AUTH_TOKEN}
    hook:
      url: https://tow-truck-bot.nl.tuna.am/api/telegram/webhook
      secret: ser_aleu_3d2a09d1-1994-482a-87b2-b9f647e64e30
  steps:
    start:
      message: |
        Здравствуйте!
        Спасибо за обращение в службу эвакуации Дежурная Машина!
        Для вызова эвакуатора нам необходимы подробности, пожалуйста, ответьте на несколько простых вопросов.
      image-path: src/main/resources/telegram/start_image.jpg
    questions:
      phone-num:
        text: Пожалуйста, предоставьте ваш номер телефона чтобы оператор мог связаться с вами после оформления заявки на вызов эвакуатора
        error: Введен некорректный номер телефона.
      text-reply:
        text1: Что бы запустить бота, пожалуйста, введите команду /start
        text2: Для продолжения взаимодействия с ботом, пожалуйста, выберите опцию из предоставленного выше списка. Если вы хотите начать с начала, введите команду /start
      vehicle-type:
        text: Выберете тип транспортного средства
      vehicle-problem:
        text: Выберите состояние транспортного средства
      current-location:
        text: Укажите адрес или координаты откуда забрать автомобиль
      destination-location:
        text: Укажите адрес или координаты куда доставить автомобиль (для этого нажмите на кнопку "поделиться", далее нажмите на "геопозиция", на открывшейся карте укажите точку куда необходимо доставить ваше транспортное средство)
      payment-method:
        text: Укажите желаемый способ оплаты
      need-docs:
        text: Нужны ли будут закрывающие документы, чек или акт выполненных работ?
      order-confirmation:
        text: Пожалуйста, проверьте ваш заказ ниже. Для отправки заказа, нажмите на кнопку оформления заказа.
      final-reply:
        text: Ваш заказ был подтвержден, пожалуйста, ожидайте звонка оператора.
    error:
      text: Упс, мне смазывают шестеренки, позвоните, пожалуйста по этому номеру для заказа эвакуатора - 8(909)-999-99-99
  forbidden-words:
    is_enabled: true
    path: src/main/resources/telegram/forbidden_words.txt
  black-listed-telegram-names:
    path: src/main/resources/telegram/black_listed_telegram_names.txt

price:
