server:
  port: 8080

spring:
  application:
    name: tow-truck-bot

telegram:
  web:
    bot-username: CarTowTruckBot
    admin-chat-id: 7895027135
    auth:
      token: ${WEB_TELEGRAM_AUTH_TOKEN}
  steps:
    start:
      message: |
        ?? ????, ??????
      button: ?????!
      image-path: src/main/resources/telegram/start_image.jpg
    options:
      message: |
        ??????, ??? ??? ????? ???????...
      dishes:
        message: |
          ?????? ? ????????? ????? ????? ???????? ? ???? ???? ? ???????
        button: ????????? ?????? ????
      option1:
        button: ????? 1
      option2:
        button: ????? 2
  forbidden-words:
    is_enabled: true
    path: src/main/resources/telegram/forbidden_words.txt